# Generated by Django 2.1.7 on 2019-02-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='task_text',
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
