# Generated by Django 2.1.7 on 2019-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20190226_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('AC', 'Active'), ('CM', 'Complete'), ('CD', 'Closed')], default='AC', max_length=2),
        ),
    ]
