# Generated by Django 2.1.7 on 2019-02-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20190226_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='task_priority',
        ),
    ]
